ALTER TABLE ledgers ADD COLUMN cover TEXT DEFAULT NULL;
ALTER TABLE ledgers ADD COLUMN description TEXT DEFAULT NULL;
ALTER TABLE ledgers ADD COLUMN is_default BOOLEAN DEFAULT 0;

ALTER TABLE accounts ADD COLUMN cover TEXT DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN description TEXT DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN is_default BOOLEAN DEFAULT 0;
